#!/bin/bash
# Available commands - quick reference
echo -e "\e[32m"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║             NMAP WEB TERMINAL - HELP                     ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "\e[0m"
echo ""
echo -e "\e[33m  HELPER SCRIPTS:\e[0m"
echo ""
echo -e "    \e[32mquickscan.sh\e[0m <subnet>        Host discovery (ping sweep)"
echo -e "    \e[32mportscan.sh\e[0m  <target> [ports] Full port + service scan"
echo -e "    \e[32mvulnscan.sh\e[0m  <target>        Vulnerability scan (NSE)"
echo -e "    \e[32mstealthscan.sh\e[0m <target>      SYN stealth scan"
echo -e "    \e[32mrecon.sh\e[0m     <target>        Full recon (whois+dns+ports+os)"
echo ""
echo -e "\e[33m  QUICK EXAMPLES:\e[0m"
echo ""
echo -e "    nmap -sn 192.168.1.0/24          # Discover hosts"
echo -e "    nmap -sV -p 80,443 target        # Check web ports"
echo -e "    nmap -A target                   # Aggressive scan"
echo -e "    nmap --script=http-enum target   # Web enumeration"
echo -e "    nmap -sU --top-ports 50 target   # UDP scan"
echo ""
echo -e "\e[33m  OTHER TOOLS:\e[0m"
echo ""
echo -e "    curl, wget, dig, whois, traceroute, netcat, tcpdump, ping"
echo ""
echo -e "\e[90m  Results saved in: /scans/\e[0m"
echo -e "\e[90m  Run 'ls /scans' to see saved results\e[0m"
echo ""
